config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy
  resources :posts, except: :index do
    resources :comments, only: [:create, :new]
  end
  resources :comments, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  content    :string           not null
#  user_id    :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string           not null
#  content    :string
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :url, presence: true

  belongs_to :user

  has_many :postsubs,
    foreign_key: :post_id,
    class_name: :Postsub,
    inverse_of: :post

  has_many :subs,
    through: :postsubs,
    source: :sub

  has_many :comments
end

app/models/postsub.rb
# == Schema Information
#
# Table name: postsubs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Postsub < ApplicationRecord
#   validates :post_id, :sub_id, presence: true

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :postsubs,
    foreign_key: :sub_id,
    class_name: :Postsub,
    inverse_of: :sub

  has_many :posts,
    through: :postsubs,
    source: :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  after_initialize :ensure_session_token
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :subs
  has_many :posts
  has_many :comments

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    user && user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password
    @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :auth_token

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"<%= form_authenticity_token %>\">".html_safe
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def ensure_login
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = params[:post_id]
    # Fail
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id] unless @comment.post_id
    # Fail

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_login

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(@post.user_id)
    @subs = @post.subs
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login(user)
      redirect_to subs_url
    else
      flash[:errors] = "Invalid login credentials"
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_login
  before_action :ensure_moderator, only: [:edit, :update]

  def ensure_moderator
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless @sub.user_id == current_user.id
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @mod = @sub.moderator
    @posts = @sub.posts
  end

  def index
    @subs = Sub.all
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.user_id == current_user.id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      # redirect_to links_url
    else
      flash[:errors] = "Error password too short"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>New Comment!</h1>

<%=flash[:errors] if flash[:errors]%>
<form action="<%= comments_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

    <input type="hidden" name="comment[post_id]" value="<%= @post %>">

    <label>Body
        <textarea name="comment[content]"></textarea>
    </label>

    <br>
    <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W5D2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if current_user %>
    <ul>
      <li><%= current_user.username %></li>
      <li><a href="<%= new_sub_url %>">Create a sub!</a></li>
      <li><a href="<%= subs_url %>">All Subs</a></li>
      <li>
          <form action="<%= session_url %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value="Logout">
          </form>
      </li>
    </ul>
  <%else%>
    <a href="<%= new_session_url %>">Sign in!</a>
  <%end%>
  
  <br>
  <br>

  <body>
    <%= yield %>
  </body>

  <% unless current_user %>
    <a href="<%= new_user_url %>">Sign up!</a>
  <% end %>
</html>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<form action="<%= posts_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
        <input type="text" name="post[title]">
    </label>
    <br>
    <label>URL:
        <input type="text" name="post[url]">
    </label>
    <br>
    <label>Content:
        <textarea name="post[content]"></textarea>
    </label>
    <br>

    <%@subs.each do |sub|%>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %><br>
    <%end%>

    <input type="submit" value="Submit">
</form>

app/views/posts/show.html.erb
<h1><a href="<%= post_url(@post) %>"><%= @post.title %></a>
     by <%= @author.username %>
</h1>

<p>Content:</p>
<%= @post.content %>

<h3>Subs</h3>
<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

<h2>Comments</h2>

<a href="<%= new_post_comment_url(@post)%>">Comment on this post!</a>

<%=flash[:errors] if flash[:errors]%>
<form action="<%= post_comments_url(@post) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

    <label>Body
        <textarea name="comment[content]"></textarea>
    </label>

    <br>
    <input type="submit" value="Submit">
</form>

<ul>
    <% @comments.each do |comment| %>
        <li>
            <a href="<%= comment_url(comment) %>"><%= comment.content %></a>
        </li>
    <% end%>
</ul>

app/views/subs/edit.html.erb
<h1>Edit your Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label>Name
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <br>
    <label>Description
        <textarea name="sub[description]">
            <%= @sub.description%>
        </textarea>
    </label>
    <input type="submit" value="Submit!">
</form>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
    <%@subs.each do |sub|%>
        <li>
            <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
        </li>
    <%end%>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>

<form action="<%= subs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Name
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <br>

    <label>Description
        <textarea name="sub[description]"><%= @sub.description %></textarea>
    </label>

    <input type="submit" value = "Submit!">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3>Description</h3>

<p><%= @sub.description%></p>

<h3>Posts</h3>
<ul>
    <% @posts.each do |post| %>
        <li>
            <a href="<%= post_url(post) %>"><%= post.title %></a>
        </li>
    <% end %>
</ul>

<a href="<%= new_post_url %>">Make New Post!</a>
<br>
<a href="<%= edit_sub_url(@sub)%>">Edit</a>

app/views/users/new.html.erb
<h1>New User!</h1>
<%= flash[:errors] if flash[:errors] %>
<form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Username
        <input type="text" name="user[username]" value="">
    </label>

    <label>Password
        <input type="text" name="user[password]" value="">
    </label>

    <input type="submit" value="create user">
</form>